// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package storagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	// rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
	// rpc FindUserByUsername (FindUserByUsernameRequest) returns (FindUserByUsernameResponse);
	// rpc FindUserById (FindUserByIdRequest) returns (FindUserByIdResponse);
	// rpc UpdateUserByUsername (UpdateUserByUsernameRequest) returns (UpdateUserByUsernameResponse);
	// rpc DeleteUserByUsername (DeleteUserByUsernameRequest) returns (DeleteUserByUsernameResponse);
	//
	// rpc CreateDocument (CreateDocumentRequest) returns (CreateDocumentResponse);
	GetDocumentById(ctx context.Context, in *GetDocumentByIdRequest, opts ...grpc.CallOption) (*GetDocumentByIdResponse, error)
	GetDocumentsByUserId(ctx context.Context, in *GetDocumentsByUserIdRequest, opts ...grpc.CallOption) (*GetDocumentsByUserIdResponse, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) GetDocumentById(ctx context.Context, in *GetDocumentByIdRequest, opts ...grpc.CallOption) (*GetDocumentByIdResponse, error) {
	out := new(GetDocumentByIdResponse)
	err := c.cc.Invoke(ctx, "/storage.v1.Storage/GetDocumentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetDocumentsByUserId(ctx context.Context, in *GetDocumentsByUserIdRequest, opts ...grpc.CallOption) (*GetDocumentsByUserIdResponse, error) {
	out := new(GetDocumentsByUserIdResponse)
	err := c.cc.Invoke(ctx, "/storage.v1.Storage/GetDocumentsByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	// rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
	// rpc FindUserByUsername (FindUserByUsernameRequest) returns (FindUserByUsernameResponse);
	// rpc FindUserById (FindUserByIdRequest) returns (FindUserByIdResponse);
	// rpc UpdateUserByUsername (UpdateUserByUsernameRequest) returns (UpdateUserByUsernameResponse);
	// rpc DeleteUserByUsername (DeleteUserByUsernameRequest) returns (DeleteUserByUsernameResponse);
	//
	// rpc CreateDocument (CreateDocumentRequest) returns (CreateDocumentResponse);
	GetDocumentById(context.Context, *GetDocumentByIdRequest) (*GetDocumentByIdResponse, error)
	GetDocumentsByUserId(context.Context, *GetDocumentsByUserIdRequest) (*GetDocumentsByUserIdResponse, error)
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) GetDocumentById(context.Context, *GetDocumentByIdRequest) (*GetDocumentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentById not implemented")
}
func (UnimplementedStorageServer) GetDocumentsByUserId(context.Context, *GetDocumentsByUserIdRequest) (*GetDocumentsByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentsByUserId not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_GetDocumentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetDocumentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.v1.Storage/GetDocumentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetDocumentById(ctx, req.(*GetDocumentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetDocumentsByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentsByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetDocumentsByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.v1.Storage/GetDocumentsByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetDocumentsByUserId(ctx, req.(*GetDocumentsByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.v1.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocumentById",
			Handler:    _Storage_GetDocumentById_Handler,
		},
		{
			MethodName: "GetDocumentsByUserId",
			Handler:    _Storage_GetDocumentsByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage_service/storage.proto",
}
