// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package storagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	FindUserByUsername(ctx context.Context, in *FindUserByUsernameRequest, opts ...grpc.CallOption) (*FindUserByUsernameResponse, error)
	FindUserById(ctx context.Context, in *FindUserByIdRequest, opts ...grpc.CallOption) (*FindUserByIdResponse, error)
	UpdateUserByUsername(ctx context.Context, in *UpdateUserByUsernameRequest, opts ...grpc.CallOption) (*UpdateUserByUsernameResponse, error)
	DeleteUserByUsername(ctx context.Context, in *DeleteUserByUsernameRequest, opts ...grpc.CallOption) (*DeleteUserByUsernameResponse, error)
	CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error)
	FindDocumentById(ctx context.Context, in *FindDocumentByIdRequest, opts ...grpc.CallOption) (*FindDocumentByIdResponse, error)
	FindDocumentByUserId(ctx context.Context, in *FindDocumentByUserIdRequest, opts ...grpc.CallOption) (*FindDocumentByUserIdResponse, error)
	UpdateDocumentById(ctx context.Context, in *UpdateDocumentByIdRequest, opts ...grpc.CallOption) (*UpdateDocumentByIdResponse, error)
	DeleteDocumentById(ctx context.Context, in *DeleteDocumentByIdRequest, opts ...grpc.CallOption) (*DeleteDocumentByIdResponse, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/Storage/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) FindUserByUsername(ctx context.Context, in *FindUserByUsernameRequest, opts ...grpc.CallOption) (*FindUserByUsernameResponse, error) {
	out := new(FindUserByUsernameResponse)
	err := c.cc.Invoke(ctx, "/Storage/FindUserByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) FindUserById(ctx context.Context, in *FindUserByIdRequest, opts ...grpc.CallOption) (*FindUserByIdResponse, error) {
	out := new(FindUserByIdResponse)
	err := c.cc.Invoke(ctx, "/Storage/FindUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) UpdateUserByUsername(ctx context.Context, in *UpdateUserByUsernameRequest, opts ...grpc.CallOption) (*UpdateUserByUsernameResponse, error) {
	out := new(UpdateUserByUsernameResponse)
	err := c.cc.Invoke(ctx, "/Storage/UpdateUserByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) DeleteUserByUsername(ctx context.Context, in *DeleteUserByUsernameRequest, opts ...grpc.CallOption) (*DeleteUserByUsernameResponse, error) {
	out := new(DeleteUserByUsernameResponse)
	err := c.cc.Invoke(ctx, "/Storage/DeleteUserByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error) {
	out := new(CreateDocumentResponse)
	err := c.cc.Invoke(ctx, "/Storage/CreateDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) FindDocumentById(ctx context.Context, in *FindDocumentByIdRequest, opts ...grpc.CallOption) (*FindDocumentByIdResponse, error) {
	out := new(FindDocumentByIdResponse)
	err := c.cc.Invoke(ctx, "/Storage/FindDocumentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) FindDocumentByUserId(ctx context.Context, in *FindDocumentByUserIdRequest, opts ...grpc.CallOption) (*FindDocumentByUserIdResponse, error) {
	out := new(FindDocumentByUserIdResponse)
	err := c.cc.Invoke(ctx, "/Storage/FindDocumentByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) UpdateDocumentById(ctx context.Context, in *UpdateDocumentByIdRequest, opts ...grpc.CallOption) (*UpdateDocumentByIdResponse, error) {
	out := new(UpdateDocumentByIdResponse)
	err := c.cc.Invoke(ctx, "/Storage/UpdateDocumentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) DeleteDocumentById(ctx context.Context, in *DeleteDocumentByIdRequest, opts ...grpc.CallOption) (*DeleteDocumentByIdResponse, error) {
	out := new(DeleteDocumentByIdResponse)
	err := c.cc.Invoke(ctx, "/Storage/DeleteDocumentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	FindUserByUsername(context.Context, *FindUserByUsernameRequest) (*FindUserByUsernameResponse, error)
	FindUserById(context.Context, *FindUserByIdRequest) (*FindUserByIdResponse, error)
	UpdateUserByUsername(context.Context, *UpdateUserByUsernameRequest) (*UpdateUserByUsernameResponse, error)
	DeleteUserByUsername(context.Context, *DeleteUserByUsernameRequest) (*DeleteUserByUsernameResponse, error)
	CreateDocument(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error)
	FindDocumentById(context.Context, *FindDocumentByIdRequest) (*FindDocumentByIdResponse, error)
	FindDocumentByUserId(context.Context, *FindDocumentByUserIdRequest) (*FindDocumentByUserIdResponse, error)
	UpdateDocumentById(context.Context, *UpdateDocumentByIdRequest) (*UpdateDocumentByIdResponse, error)
	DeleteDocumentById(context.Context, *DeleteDocumentByIdRequest) (*DeleteDocumentByIdResponse, error)
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedStorageServer) FindUserByUsername(context.Context, *FindUserByUsernameRequest) (*FindUserByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUserByUsername not implemented")
}
func (UnimplementedStorageServer) FindUserById(context.Context, *FindUserByIdRequest) (*FindUserByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUserById not implemented")
}
func (UnimplementedStorageServer) UpdateUserByUsername(context.Context, *UpdateUserByUsernameRequest) (*UpdateUserByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserByUsername not implemented")
}
func (UnimplementedStorageServer) DeleteUserByUsername(context.Context, *DeleteUserByUsernameRequest) (*DeleteUserByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserByUsername not implemented")
}
func (UnimplementedStorageServer) CreateDocument(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDocument not implemented")
}
func (UnimplementedStorageServer) FindDocumentById(context.Context, *FindDocumentByIdRequest) (*FindDocumentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDocumentById not implemented")
}
func (UnimplementedStorageServer) FindDocumentByUserId(context.Context, *FindDocumentByUserIdRequest) (*FindDocumentByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDocumentByUserId not implemented")
}
func (UnimplementedStorageServer) UpdateDocumentById(context.Context, *UpdateDocumentByIdRequest) (*UpdateDocumentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocumentById not implemented")
}
func (UnimplementedStorageServer) DeleteDocumentById(context.Context, *DeleteDocumentByIdRequest) (*DeleteDocumentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocumentById not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_FindUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).FindUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/FindUserByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).FindUserByUsername(ctx, req.(*FindUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_FindUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).FindUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/FindUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).FindUserById(ctx, req.(*FindUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_UpdateUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).UpdateUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/UpdateUserByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).UpdateUserByUsername(ctx, req.(*UpdateUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_DeleteUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/DeleteUserByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteUserByUsername(ctx, req.(*DeleteUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/CreateDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CreateDocument(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_FindDocumentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDocumentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).FindDocumentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/FindDocumentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).FindDocumentById(ctx, req.(*FindDocumentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_FindDocumentByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDocumentByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).FindDocumentByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/FindDocumentByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).FindDocumentByUserId(ctx, req.(*FindDocumentByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_UpdateDocumentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).UpdateDocumentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/UpdateDocumentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).UpdateDocumentById(ctx, req.(*UpdateDocumentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_DeleteDocumentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteDocumentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/DeleteDocumentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteDocumentById(ctx, req.(*DeleteDocumentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Storage_CreateUser_Handler,
		},
		{
			MethodName: "FindUserByUsername",
			Handler:    _Storage_FindUserByUsername_Handler,
		},
		{
			MethodName: "FindUserById",
			Handler:    _Storage_FindUserById_Handler,
		},
		{
			MethodName: "UpdateUserByUsername",
			Handler:    _Storage_UpdateUserByUsername_Handler,
		},
		{
			MethodName: "DeleteUserByUsername",
			Handler:    _Storage_DeleteUserByUsername_Handler,
		},
		{
			MethodName: "CreateDocument",
			Handler:    _Storage_CreateDocument_Handler,
		},
		{
			MethodName: "FindDocumentById",
			Handler:    _Storage_FindDocumentById_Handler,
		},
		{
			MethodName: "FindDocumentByUserId",
			Handler:    _Storage_FindDocumentByUserId_Handler,
		},
		{
			MethodName: "UpdateDocumentById",
			Handler:    _Storage_UpdateDocumentById_Handler,
		},
		{
			MethodName: "DeleteDocumentById",
			Handler:    _Storage_DeleteDocumentById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage_service/storage.proto",
}
