// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package aipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AIClient is the client API for AI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIClient interface {
	Question(ctx context.Context, in *QuestionRequest, opts ...grpc.CallOption) (*QuestionResponse, error)
	UpdateDocumentById(ctx context.Context, in *UpdateDocumentByIdRequest, opts ...grpc.CallOption) (*UpdateDocumentByIdResponse, error)
}

type aIClient struct {
	cc grpc.ClientConnInterface
}

func NewAIClient(cc grpc.ClientConnInterface) AIClient {
	return &aIClient{cc}
}

func (c *aIClient) Question(ctx context.Context, in *QuestionRequest, opts ...grpc.CallOption) (*QuestionResponse, error) {
	out := new(QuestionResponse)
	err := c.cc.Invoke(ctx, "/ai.v1.AI/Question", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIClient) UpdateDocumentById(ctx context.Context, in *UpdateDocumentByIdRequest, opts ...grpc.CallOption) (*UpdateDocumentByIdResponse, error) {
	out := new(UpdateDocumentByIdResponse)
	err := c.cc.Invoke(ctx, "/ai.v1.AI/UpdateDocumentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServer is the server API for AI service.
// All implementations must embed UnimplementedAIServer
// for forward compatibility
type AIServer interface {
	Question(context.Context, *QuestionRequest) (*QuestionResponse, error)
	UpdateDocumentById(context.Context, *UpdateDocumentByIdRequest) (*UpdateDocumentByIdResponse, error)
	mustEmbedUnimplementedAIServer()
}

// UnimplementedAIServer must be embedded to have forward compatible implementations.
type UnimplementedAIServer struct {
}

func (UnimplementedAIServer) Question(context.Context, *QuestionRequest) (*QuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Question not implemented")
}
func (UnimplementedAIServer) UpdateDocumentById(context.Context, *UpdateDocumentByIdRequest) (*UpdateDocumentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocumentById not implemented")
}
func (UnimplementedAIServer) mustEmbedUnimplementedAIServer() {}

// UnsafeAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServer will
// result in compilation errors.
type UnsafeAIServer interface {
	mustEmbedUnimplementedAIServer()
}

func RegisterAIServer(s *grpc.Server, srv AIServer) {
	s.RegisterService(&_AI_serviceDesc, srv)
}

func _AI_Question_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServer).Question(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.v1.AI/Question",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServer).Question(ctx, req.(*QuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AI_UpdateDocumentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServer).UpdateDocumentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.v1.AI/UpdateDocumentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServer).UpdateDocumentById(ctx, req.(*UpdateDocumentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.AI",
	HandlerType: (*AIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Question",
			Handler:    _AI_Question_Handler,
		},
		{
			MethodName: "UpdateDocumentById",
			Handler:    _AI_UpdateDocumentById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai_service/ai.proto",
}
